apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-application
  namespace: argocd
spec: 
  source:
    repoURL: https://github.com/Aditi336/argocd-app.git
    targetRevision: HEAD 
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 